what are these errors?
[martin@localhost cl_nbdev_test]$ nbdev_install_git_hooks
Traceback (most recent call last):
  File "/home/martin/.local/bin/nbdev_install_git_hooks", line 5, in <module>
    from nbdev.cli import nbdev_install_git_hooks
  File "/home/martin/.local/lib/python3.9/site-packages/nbdev/cli.py", line 10, in <module>
    from .export2html import *
  File "/home/martin/.local/lib/python3.9/site-packages/nbdev/export2html.py", line 16, in <module>
    from .showdoc import *
  File "/home/martin/.local/lib/python3.9/site-packages/nbdev/showdoc.py", line 11, in <module>
    from nbconvert import HTMLExporter
  File "/home/martin/.local/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/martin/.local/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/home/martin/.local/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 14, in <module>
    from nbconvert.filters.highlight import Highlight2HTML
  File "/home/martin/.local/lib/python3.9/site-packages/nbconvert/filters/__init__.py", line 7, in <module>
    from .strings import *
  File "/home/martin/.local/lib/python3.9/site-packages/nbconvert/filters/strings.py", line 22, in <module>
    from defusedxml import cElementTree as ElementTree
  File "/usr/lib/python3.9/site-packages/defusedxml/cElementTree.py", line 13, in <module>
    raise ImportError("cElementTree has been removed from Python 3.9")
ImportError: cElementTree has been removed from Python 3.9